# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(default=b'', max_length=1)),
                ('stream', models.CharField(default=b'', max_length=3)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(default=b'', max_length=8)),
                ('slots', models.CharField(default=b'', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject', models.CharField(choices=[(b'1', b'CD'), (b'2', b'CC'), (b'3', b'NP'), (b'4', b'MAP'), (b'5', b'AI'), (b'6', b'EE')], max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Tid', models.CharField(default=b'', max_length=6, primary_key=True, serialize=False)),
                ('password', models.CharField(default=b'', max_length=10)),
                ('name', models.CharField(default=b'', max_length=20)),
                ('TT', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject'),
        ),
        migrations.AddField(
            model_name='batch',
            name='TT',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='batch',
            name='teachers',
            field=models.ManyToManyField(to='schedule.Teacher'),
        ),
    ]
