# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180211_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[(b'0', b'-'), (b'1', b'CD'), (b'2', b'CC'), (b'3', b'NP'), (b'4', b'MAP'), (b'5', b'AI'), (b'6', b'EE')], max_length=1, primary_key=True, serialize=False),
        ),
    ]
