# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180211_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Sid',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
