# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20180211_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='TT',
        ),
        migrations.AddField(
            model_name='batch',
            name='TT',
            field=models.ManyToManyField(to='schedule.Schedule'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='TT',
        ),
        migrations.AddField(
            model_name='teacher',
            name='TT',
            field=models.ManyToManyField(to='schedule.Schedule'),
        ),
    ]
