# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20180211_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default=b'', max_length=9),
        ),
    ]
