# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20180212_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('Sid',)},
        ),
    ]
